### ISSUE TITLE
SyntaxError: Unexpected token 'export' as of April 06, 2021

### ISSUE THREAD

**Issue by dwemel** [gkoehler/LogiCircleDownloader#16]
As of this morning, I receive the following error. 
Would something have changed at the LogiCircle side? Or did I do something wrong?

`(node:16713) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of null
    at authorize (/home/openhabian/LogiCircleDownloader/downloader.js:21:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async run (/home/openhabian/LogiCircleDownloader/downloader.js:95:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16713) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16713) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

When I use the node --trace-warnings, I receive the following
`(node:16948) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/home/openhabian/LogiCircleDownloader/start.sh:1
export LOGI_EMAIL="myemail@address.com"
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
`

Thanks in advance for helping me out :-)

**Comment by hischampion** [comment]
Have you tried running npm install again? I believe that dependencies may have changed.

**Comment by hischampion** [comment]
Looking into this more, it appears that Logitech made changes to their login endpoint we're using. It is telling us we are not authorized. I am guessing it's because there is a captcha integrated on the website. This would be hard to replicate in a command line application and is, in fact, indenteded to prevent us from using their API in this way.

Going forward, this tool will have to migrate to login using a legimate API account. I will check on how to do this.

**Comment by dwemel** [comment]
Thank you. You are the best. I wish I could help. Maybe there's a way for me to do a small contribution or something?
________________________________

**Comment by divemasterjm** [comment]
+1

**Comment by divemasterjm** [comment]
@hischampion did you make any improvements? 

thanks

**Comment by WhiskeyDelta1** [comment]
Also experiencing the same issue.
(node:14660) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of null at authorize /mnt/f/Archive/User/Circle/downloader.js:20:32) at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by mofesola** [comment]
I am experiencing the same issue:

`(node:1018) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of null
    at authorize (/usr/src/app/downloader.js:21:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1018) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1018) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by microsofa** [comment]
Same issue, any luck with a solution so far? Also, FWIW I'd be willing to donate a few bucks into a coffee fund to expedite a solution. 

Does anyone have an alternate solution? Clicking on each video to download is not feasible.

**Comment by MontroseSt** [comment]
Same issue here, however I don't think it's a captcha issue. The error occured after updating npm to v7.11.2

```
The action “Run Shell Script” encountered an error: “/LogiCircleDownloader/downloader.js:21
    let sessionCookie = cookie.match(/prod_session=[^;]+/)[0];
                               ^

TypeError: Cannot read property 'match' of null
    at authorize (/LogiCircleDownloader/downloader.js:21:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/LogiCircleDownloader/downloader.js:95:25)”
```

**Comment by divemasterjm** [comment]
@hischampion any news? thanks

**Comment by hischampion** [comment]
I have not had any success finding a real developer API account that we can use. I suspect this may be a deliberate choice of Logitech. However, I believe we may have a work around. Since the app currently uses the web login endpoint to get credentials for downloading vidoes, we are blocked out by the addition of captcha functions on the web login screen.

1. We can research how the iOS and Android apps do login (which may bypass Captcha)
2. We can pop up a browser to let a user manually log in while running the script (will not be able to run headless) 

I am going to try to make a proof of concept for #2 tonight or tomorrow.

**Comment by divemasterjm** [comment]
@hischampion i've found https://github.com/evanjd/python-logi-circle (legacy), where there is a function you can download the last video and also all videos, maybe you can have a view on this code.
i've tried and it works, the only thing is that is downloading all videos every time is called, my skills in python are 0.
if you need help on testing in any proof of concept i will be ready for it.

**Comment by hischampion** [comment]
That's great! I will take a look at that. I have made a PR you can also test. #18

**Comment by hischampion** [comment]
Looks like that Python libarary has some tricks I can test out, which would avoid needing to login with the browser.
There are two new options you're presenting:
1. Python tricks (using Logi's private API)
1. Getting develper creds like the H.A. project (using Logi's Public API)

**Comment by slimnux** [comment]
Hello everyone.
I can't get it to run even with the browser login. I was running the original script with OpenWSL within W10. And I don't have Chrome installed.
Can anyone help me to get this up and running?
Thanks again.

**Comment by kaktuspalme** [comment]
If anyone is interested. I changed the code locally so that it uses the refresh token and code_verifier to get a new access_token and refresh_token from the /identity/oauth2/token access point everytime I start the script.
For the initial login I just logged in by the browser and extracted the necessary infos from there ("refresh_token", "code_verifier"). I put those infos in a json file.

I don't know yet how reliable that method is, for example how long the code_verifier together with the refresh_token works. But at least the last 3 days the script was working fine by that way. And another downside is that you have to get the necessary infos manually by login with a browser and extract the infos from there.

**Comment by MontroseSt** [comment]
Thank you, @kaktuspalme! Can the updated code be downloaded somewhere? Can you include a example json file for the token?

**Comment by kaktuspalme** [comment]
@MontroseSt I haven't published the code yet but will do so as soon as I have some free time for that.

**Comment by dwemel** [comment]
@kaktuspalme , any chance you would find the time to upload your code?

**Comment by kaktuspalme** [comment]
@dwemel Sorry that it took so long. I just pushed the code to my forked repository.
https://github.com/kaktuspalme/LogiCircleDownloader

Look into config.json, there you can define the download directory (needs to exist) and you have to put in the code_verifier and the refresh_token from the browser session.

You can grab it from your browser after the login. In the developer tools network tab you find it in the POST Request to https://accounts.logi.com/identity/oauth2/token.
code_verifier is in the Request, refresh_token in the response.

I hope it helps, I don't know how stable this method is. I don't have logi circle anymore.

**Comment by dwemel** [comment]
You are amazing!
This works 🙂
________________________________
