### ISSUE TITLE
TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by slimnux** [gkoehler/LogiCircleDownloader#17]
Hey everyone.
Has of yesterday mine is giving me the following error message:
" TypeError: Cannot read property 'match' of null "

Is this happening with someone else?

Thanks again for helping us out!
Regards.

**Comment by deepcoder** [comment]
ditto!
thx for any ideas!

```
(node:1181) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of null
(node:1181) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of null
    at authorize (/home/user/logi_downloader/downloader.js:21:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/home/user/logi_downloader/downloader.js:102:25)
```

**Comment by hischampion** [comment]
Looking into this more, it appears that Logitech made changes to their login endpoint we're using. It is telling us we are not authorized. I am guessing it's because there is a captcha integrated on the website. This would be hard to replicate in a command line application and is, in fact, indenteded to prevent us from using their API in this way.

Going forward, this tool will have to migrate to login using a legimate API account. I will check on how to do this.
