### ISSUE TITLE
Instructions to set up

### ISSUE THREAD

**Issue by felsmann** [gkoehler/LogiCircleDownloader#3]
Thanks for creating such a great option for Logi Circle.  Can you please provide a but more details on the install for us less Tech savvy?

Thanks

**Comment by cnmarch6** [comment]
anyone?

**Comment by thomasthechan** [comment]
I, too, would love some further instruction

**Comment by gkoehler** [comment]
Thanks for the feedback! Unfortunately, I can't offer any support since this is a low-level tool and a hobby project. That being said, if you know how to use `npm` and some command-line basics, you should be able to get started based on the instructions in the readme. I'm completely open to pull requests if someone wants to type up a more comprehensive guide, too.

**Comment by nikpawlak** [comment]
Heres a guide i just typed up on installing NPM on macOS

##Install Node
1. Install XCode [Mac App Store](https://itunes.apple.com/us/app/xcode/id497799835?mt=12)
2. In Terminal Install homebrew  `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
3. In Terminal Install Node `brew install node`
4. Check installed versions of node and npm (node package manager) in terminal `node -v` and `npm -v`

Not sure where to go after this point.
